/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;
import DBmanage.DBconnUser;
import MainPackeg.UserInfoForSalesPerson;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.text.*;
import java.util.Date;
/**
 *
 * @author romio-pc
 */
public class AdministrationUser extends javax.swing.JFrame {
    
    /**
     * Creates new form User_aceptence
     */
    String table_username="";
    DefaultTableModel model;
    DBconnUser db=new DBconnUser();
    public AdministrationUser() {
        initComponents();
        userAcpet();
        
    }
    public AdministrationUser(String user) {
        initComponents();
        lvlusernameshow.setText(user);
        userAcpet();
    }
    public void userAcpet(){
        
        model=(DefaultTableModel) u_acpetence.getModel();
        u_acpetence.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 16));
        for(UserInfoForSalesPerson u : db.acceptUser()){
            Object[] row= {u.getName(),u.getMobile(),u.getAddress(),u.getaccept(),u.getCurrent_time()};
            model.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        u_acpetence = new javax.swing.JTable();
        btnAuthorization = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        lvlusernameshow = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        u_acpetence.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        u_acpetence.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Name", "Mobile No.", "Address", "Authorization", "Signup Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        u_acpetence.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                u_acpetenceMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(u_acpetence);
        if (u_acpetence.getColumnModel().getColumnCount() > 0) {
            u_acpetence.getColumnModel().getColumn(0).setResizable(false);
            u_acpetence.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 1060, 270));

        btnAuthorization.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnAuthorization.setText("Change Authorization");
        btnAuthorization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuthorizationActionPerformed(evt);
            }
        });
        jPanel1.add(btnAuthorization, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 198, -1));

        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 70, -1));

        lvlusernameshow.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lvlusernameshow, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 30, 90, 20));

        jLabel1.setForeground(new java.awt.Color(204, 255, 102));
        jLabel1.setText("USER");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 30, 50, -1));

        jButton2.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jButton2.setText("Log out");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 60, 80, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PrintAndDesign/LOGOHeader.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 160, 60));

        jButton3.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 460, 70, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void u_acpetenceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_u_acpetenceMouseClicked
        
    }//GEN-LAST:event_u_acpetenceMouseClicked

    private void btnAuthorizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuthorizationActionPerformed
        int selectedRowIndex = u_acpetence.getSelectedRow();
        
        if (selectedRowIndex>=0){
        table_username= model.getValueAt(selectedRowIndex, 0).toString();
        String auth="";
        String authupdate="";
        
        auth=model.getValueAt(selectedRowIndex, 3).toString();
        if(auth.equals("yes")){
            authupdate="no";
        }else if(auth.equals("no")){
            authupdate="yes";
        }
        
        int dialogResult = JOptionPane.showConfirmDialog(this, "Are You Sure Want to Change Autorization?", "Warning", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
                if (table_username != "") {
                    DateFormat updt = new SimpleDateFormat("yyyy-mm-dd HH:mm:ss");
                    Date date = new Date();
                    String t = updt.format(date).toString();
                   
                    db.updateAuthorization(table_username, authupdate,t);
                    int rowCount = model.getRowCount();
                    for (int i = rowCount - 1; i >= 0; i--) {
                        model.removeRow(i);
                    }
                    userAcpet();
                }
        }
        }else{
        JOptionPane.showMessageDialog(this, "No Selected Row", "Try Again", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAuthorizationActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String u=lvlusernameshow.getText();
        new AfterLogIn(u).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        new Main_LogIn().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministrationUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministrationUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministrationUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministrationUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministrationUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAuthorization;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lvlusernameshow;
    private javax.swing.JTable u_acpetence;
    // End of variables declaration//GEN-END:variables
}
