/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import DBmanage.DBconnUser;
import javax.swing.JOptionPane;

/**
 *
 * @author romio-pc
 */
public class Main_LogIn extends javax.swing.JFrame {

    /**
     * Creates new form Main_LogIn
     */
    public Main_LogIn() {
        initComponents();
        txtarea.setVisible(false);
        jScrollPane1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tbxUN = new javax.swing.JTextField();
        btnLogIn = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btnChangeP = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        passbox = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        btnLogIn1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtarea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PrintAndDesign/output_jKyQqx.gif"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 680, 98));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PrintAndDesign/right-sc44.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 110, 90));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PrintAndDesign/left-sc44.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, 110, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 140));

        jPanel2.setBackground(new java.awt.Color(36, 47, 65));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Username");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 69, 22));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Password");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 69, 22));

        tbxUN.setBackground(new java.awt.Color(36, 47, 65));
        tbxUN.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        tbxUN.setForeground(new java.awt.Color(255, 255, 255));
        tbxUN.setText("Enter user name");
        tbxUN.setBorder(null);
        tbxUN.setCaretColor(new java.awt.Color(255, 255, 255));
        tbxUN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbxUNMouseClicked(evt);
            }
        });
        tbxUN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbxUNActionPerformed(evt);
            }
        });
        jPanel2.add(tbxUN, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 210, 20));

        btnLogIn.setBackground(new java.awt.Color(102, 102, 102));
        btnLogIn.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        btnLogIn.setForeground(new java.awt.Color(255, 255, 255));
        btnLogIn.setText("Log In");
        btnLogIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLogInMouseReleased(evt);
            }
        });
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 70, -1));

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("New Sign UP");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton3MouseReleased(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 226, -1));

        btnChangeP.setBackground(new java.awt.Color(102, 102, 102));
        btnChangeP.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        btnChangeP.setForeground(new java.awt.Color(255, 255, 255));
        btnChangeP.setText("Change Password");
        btnChangeP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnChangePMouseReleased(evt);
            }
        });
        jPanel2.add(btnChangeP, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 226, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 30, 200));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 220, 10));

        passbox.setBackground(new java.awt.Color(36, 47, 65));
        passbox.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        passbox.setForeground(new java.awt.Color(255, 255, 255));
        passbox.setText("jPasswordField1");
        passbox.setBorder(null);
        passbox.setCaretColor(new java.awt.Color(255, 255, 255));
        passbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passboxMouseClicked(evt);
            }
        });
        passbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passboxActionPerformed(evt);
            }
        });
        jPanel2.add(passbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 200, 220, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PrintAndDesign/LOGOHeader1.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel5MouseExited(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 30, 360, 240));

        btnLogIn1.setBackground(new java.awt.Color(102, 102, 102));
        btnLogIn1.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        btnLogIn1.setForeground(new java.awt.Color(255, 255, 255));
        btnLogIn1.setText("Exit");
        btnLogIn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLogIn1MouseReleased(evt);
            }
        });
        btnLogIn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogIn1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogIn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 320, 110, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PrintAndDesign/output_KMwGl8.gif"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 250, 140));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 220, 10));

        jScrollPane1.setBorder(null);

        txtarea.setEditable(false);
        txtarea.setBackground(new java.awt.Color(36, 47, 65));
        txtarea.setColumns(20);
        txtarea.setFont(new java.awt.Font("Lucida Calligraphy", 0, 13)); // NOI18N
        txtarea.setForeground(new java.awt.Color(255, 255, 255));
        txtarea.setRows(5);
        txtarea.setText("The Software Application was build \nfor University course OOP(JAVA).\nIt's not for Commercial uses.\nIt was build and developed by Md.\nRafiul Hassan (Student of SWE,DIU) \nunder Supervision of \nMr. Md. Anwar Hossen \nLecturer,Department of \nSoftware Engineering\nDaffodil International University");
        txtarea.setBorder(null);
        jScrollPane1.setViewportView(txtarea);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 60, 290, 200));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 1100, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        
    }//GEN-LAST:event_btnLogInActionPerformed

    private void btnLogInMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogInMouseReleased
        String pass= new String(passbox.getPassword());
        DBconnUser lgn= new DBconnUser();
        lgn.checkLogIn(tbxUN.getText(), pass);
        if(DBconnUser.visualCheck==false)
            JOptionPane.showMessageDialog(this, "Wrong Username or Password or approval pending", "Log in failed!", JOptionPane.ERROR_MESSAGE);
        else
        {
            //JOptionPane.showMessageDialog(this, "Successfully Logged in", "welcome", JOptionPane.INFORMATION_MESSAGE);
     
           //AfterLogIn object=new AfterLogIn();
           //object.setVisible(true);
           String u = tbxUN.getText();
           new AfterLogIn(u).setVisible(true);
           this.dispose();
        }
    }//GEN-LAST:event_btnLogInMouseReleased

    private void jButton3MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseReleased
        new UserSignUp().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton3MouseReleased

    private void btnChangePMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangePMouseReleased
        new PassChanger().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnChangePMouseReleased

    private void tbxUNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbxUNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbxUNActionPerformed

    private void passboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passboxActionPerformed

    private void passboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passboxMouseClicked
        passbox.setText("");
    }//GEN-LAST:event_passboxMouseClicked

    private void tbxUNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbxUNMouseClicked
        tbxUN.setText("");
    }//GEN-LAST:event_tbxUNMouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnLogIn1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogIn1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogIn1MouseReleased

    private void btnLogIn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogIn1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnLogIn1ActionPerformed

    private void jLabel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseEntered
        jLabel5.setVisible(false);
        jScrollPane1.setVisible(true);
        txtarea.setVisible(true);
        
        
    }//GEN-LAST:event_jLabel5MouseEntered

    private void jLabel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseExited
        txtarea.setVisible(false);
        jScrollPane1.setVisible(false);
        jLabel5.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                new Main_LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangeP;
    private javax.swing.JButton btnLogIn;
    private javax.swing.JButton btnLogIn1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPasswordField passbox;
    private javax.swing.JTextField tbxUN;
    private javax.swing.JTextArea txtarea;
    // End of variables declaration//GEN-END:variables
}
