/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import DBmanage.DBconnProduct;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import MainPackeg.ProductInfo;

/**
 *
 * @author romio-pc
 */
public class ProductInfoUpdate extends javax.swing.JFrame {
    String id = "";
    DefaultTableModel model1;
    DBconnProduct pro =new DBconnProduct();
    /**
     * Creates new form AddProduct
     */
    public ProductInfoUpdate() {
        initComponents();
        model1 = (DefaultTableModel) tblProduct.getModel();
    }
    public ProductInfoUpdate(String user) {
        initComponents();
        model1 = (DefaultTableModel) tblProduct.getModel();
        lvlusernameshow.setText(user);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tbxsearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tbxproprec = new javax.swing.JTextField();
        tbxpname = new javax.swing.JTextField();
        tbxcname = new javax.swing.JTextField();
        tbxcost = new javax.swing.JTextField();
        cboxQupdate = new javax.swing.JComboBox<>();
        tbxquantity = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lvlusernameshow = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        btnLogIn1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbxsearch.setBackground(new java.awt.Color(51, 51, 51));
        tbxsearch.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        tbxsearch.setForeground(new java.awt.Color(255, 255, 255));
        tbxsearch.setText("Type Product/Company Name");
        tbxsearch.setBorder(null);
        tbxsearch.setCaretColor(new java.awt.Color(255, 255, 255));
        tbxsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbxsearchMouseClicked(evt);
            }
        });
        jPanel1.add(tbxsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 280, -1));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        tblProduct.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Name", "Company", "Cost", "Profit %", "Quantity", "Update by", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProduct);
        if (tblProduct.getColumnModel().getColumnCount() > 0) {
            tblProduct.getColumnModel().getColumn(0).setResizable(false);
            tblProduct.getColumnModel().getColumn(1).setResizable(false);
            tblProduct.getColumnModel().getColumn(2).setResizable(false);
            tblProduct.getColumnModel().getColumn(3).setResizable(false);
            tblProduct.getColumnModel().getColumn(4).setResizable(false);
            tblProduct.getColumnModel().getColumn(5).setResizable(false);
            tblProduct.getColumnModel().getColumn(6).setResizable(false);
            tblProduct.getColumnModel().getColumn(7).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 1080, 180));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Profit %");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 60, -1));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Product Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 90, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Company");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 60, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cost");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 60, -1));

        tbxproprec.setBackground(new java.awt.Color(51, 51, 51));
        tbxproprec.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        tbxproprec.setForeground(new java.awt.Color(255, 255, 255));
        tbxproprec.setBorder(null);
        tbxproprec.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(tbxproprec, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 310, -1));

        tbxpname.setBackground(new java.awt.Color(51, 51, 51));
        tbxpname.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        tbxpname.setForeground(new java.awt.Color(255, 255, 255));
        tbxpname.setBorder(null);
        tbxpname.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(tbxpname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 310, -1));

        tbxcname.setBackground(new java.awt.Color(51, 51, 51));
        tbxcname.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        tbxcname.setForeground(new java.awt.Color(255, 255, 255));
        tbxcname.setBorder(null);
        tbxcname.setCaretColor(new java.awt.Color(255, 255, 255));
        tbxcname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbxcnameActionPerformed(evt);
            }
        });
        jPanel1.add(tbxcname, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 310, -1));

        tbxcost.setBackground(new java.awt.Color(51, 51, 51));
        tbxcost.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        tbxcost.setForeground(new java.awt.Color(255, 255, 255));
        tbxcost.setBorder(null);
        tbxcost.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(tbxcost, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 310, -1));

        cboxQupdate.setBackground(new java.awt.Color(102, 102, 102));
        cboxQupdate.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        cboxQupdate.setForeground(new java.awt.Color(255, 255, 255));
        cboxQupdate.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ADD", "DELETE" }));
        cboxQupdate.setBorder(null);
        jPanel1.add(cboxQupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 80, -1));

        tbxquantity.setBackground(new java.awt.Color(51, 51, 51));
        tbxquantity.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        tbxquantity.setForeground(new java.awt.Color(255, 255, 255));
        tbxquantity.setText("0");
        tbxquantity.setBorder(null);
        tbxquantity.setCaretColor(new java.awt.Color(255, 255, 255));
        jPanel1.add(tbxquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 320, 90, -1));

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 400, -1, -1));

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, -1, -1));

        jLabel6.setForeground(new java.awt.Color(204, 255, 102));
        jLabel6.setText("USER");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, 50, -1));

        lvlusernameshow.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lvlusernameshow, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 20, 90, 20));

        jButton5.setBackground(new java.awt.Color(102, 102, 102));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Log out");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 50, 80, -1));

        btnback.setBackground(new java.awt.Color(102, 102, 102));
        btnback.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        btnback.setForeground(new java.awt.Color(255, 255, 255));
        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel1.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        btnLogIn1.setBackground(new java.awt.Color(102, 102, 102));
        btnLogIn1.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        btnLogIn1.setForeground(new java.awt.Color(255, 255, 255));
        btnLogIn1.setText("Exit");
        btnLogIn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLogIn1MouseReleased(evt);
            }
        });
        btnLogIn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogIn1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogIn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 470, 110, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PrintAndDesign/LOGOHeader.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 160, 60));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 280, 10));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 310, 10));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 310, 10));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 310, 10));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 90, 10));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 310, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 530));

        setSize(new java.awt.Dimension(1116, 559));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbxcnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbxcnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbxcnameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int caSe=1;
        if(id=="" && !tbxpname.getText().equals("") && !tbxcname.getText().equals("") && !tbxcost.getText().equals("") && !tbxproprec.getText().equals("") && !tbxquantity.getText().equals("")){
            pro.productInsart(tbxpname.getText(), tbxcname.getText(), tbxcost.getText(), tbxproprec.getText(), tbxquantity.getText(),lvlusernameshow.getText());
            JOptionPane.showMessageDialog(this, "Successfully updated", "Product info", JOptionPane.INFORMATION_MESSAGE);
        
        }else if(id!="" && !tbxpname.getText().equals("") && !tbxcname.getText().equals("") && !tbxcost.getText().equals("")){
            String qu = pro.productQuantityCheck(id);
            int qResult;
            int qInDB = Integer.parseInt(qu);

            int qInTbx = Integer.parseInt(tbxquantity.getText());

            if (cboxQupdate.getSelectedItem().toString().equals("ADD")) {
                qResult = qInDB + qInTbx;
            } else {
                qResult = qInDB - qInTbx;
            }
            
            if(qResult>=0){
                DateFormat updt = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                    Date date = new Date();
                    String t = updt.format(date).toString();
            String k=pro.productInfoUpdate(id,tbxpname.getText(),tbxcname.getText(), tbxcost.getText(), tbxproprec.getText(), String.valueOf(qResult),lvlusernameshow.getText(),t);
            JOptionPane.showMessageDialog(this, k, "Product info", JOptionPane.INFORMATION_MESSAGE);
            }else if(qResult<=0){
            caSe=2;
            }
        }
        else
            JOptionPane.showMessageDialog(this, "Some Field Empty", "Product Info", JOptionPane.ERROR_MESSAGE);
        if(caSe==2)
            JOptionPane.showMessageDialog(this, "Quantity Can't be Negative", "Invalid Input", JOptionPane.ERROR_MESSAGE);
        
        id="";
        tbxpname.setText("");
        tbxcname.setText("");
        tbxcost.setText("");
        tbxproprec.setText("");
        tbxquantity.setText("0");
        ArrayList<ProductInfo> p = new ArrayList();
        p = pro.searchProductInfo(tbxsearch.getText());
        model1.setRowCount(0);
        for (int i = 0; i < p.size(); i++) {
            Object[] row = {p.get(i).getpId(), p.get(i).getPname(), p.get(i).getCname(), p.get(i).getCost(), p.get(i).getProfit(), p.get(i).getQuqntity(),p.get(i).getUser(),p.get(i).getDate()};
            model1.addRow(row);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ArrayList<ProductInfo> p = new ArrayList();
        p = pro.searchProductInfo(tbxsearch.getText());
        model1.setRowCount(0);
        for (int i = 0; i < p.size(); i++) {
            Object[] row = {p.get(i).getpId(), p.get(i).getPname(), p.get(i).getCname(), p.get(i).getCost(), p.get(i).getProfit(), p.get(i).getQuqntity(),p.get(i).getUser(),p.get(i).getDate()};
            model1.addRow(row);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        id="";
        tbxpname.setText("");
        tbxcname.setText("");
        tbxcost.setText("");
        tbxproprec.setText("");
        tbxquantity.setText("");
        tblProduct.getSelectionModel().clearSelection();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new Main_LogIn().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        String u=lvlusernameshow.getText();
        new AfterLogIn(u).setVisible(true);
        this.dispose();  
    }//GEN-LAST:event_btnbackActionPerformed

    private void tbxsearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbxsearchMouseClicked
        tbxsearch.setText("");
    }//GEN-LAST:event_tbxsearchMouseClicked

    private void tblProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductMouseClicked
        int selectedRowIndex = tblProduct.getSelectedRow();
        tbxpname.setText(model1.getValueAt(selectedRowIndex, 1).toString());
        tbxcname.setText(model1.getValueAt(selectedRowIndex, 2).toString());
        tbxcost.setText(model1.getValueAt(selectedRowIndex, 3).toString());
        tbxproprec.setText(model1.getValueAt(selectedRowIndex, 4).toString());
        //tbxquantity.setText(model1.getValueAt(selectedRowIndex, 5).toString());
        id = model1.getValueAt(selectedRowIndex, 0).toString();
        
    }//GEN-LAST:event_tblProductMouseClicked

    private void btnLogIn1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogIn1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogIn1MouseReleased

    private void btnLogIn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogIn1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnLogIn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductInfoUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductInfoUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductInfoUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductInfoUpdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductInfoUpdate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogIn1;
    private javax.swing.JButton btnback;
    private javax.swing.JComboBox<String> cboxQupdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel lvlusernameshow;
    private javax.swing.JTable tblProduct;
    private javax.swing.JTextField tbxcname;
    private javax.swing.JTextField tbxcost;
    private javax.swing.JTextField tbxpname;
    private javax.swing.JTextField tbxproprec;
    private javax.swing.JTextField tbxquantity;
    private javax.swing.JTextField tbxsearch;
    // End of variables declaration//GEN-END:variables
}
