package Gui;
import DBmanage.DBconnProduct;
import DBmanage.DBconnVoucherCustomer;
import autocomplete.AutoSuggestor;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import MainPackeg.CustomerInfo;
import MainPackeg.ProductInfo;
import DBmanage.DBconnCustomer;
import DBmanage.DBconnPaymentInstallments;
import DBmanage.DBconnVoucherDetails;
/**
 *
 * @author romio-pc
 */
public class SaleProduct extends javax.swing.JFrame {
    String customerT="new";
    String tblselect="";
    DefaultTableModel model;
    DBconnProduct pro =new DBconnProduct();
    DBconnCustomer cus=new DBconnCustomer();
    DBconnVoucherCustomer vc=new DBconnVoucherCustomer();
    DBconnVoucherDetails vd=new DBconnVoucherDetails();
    DBconnPaymentInstallments pi=new DBconnPaymentInstallments();
    /**
     * Creates new form SaleProduct
     */
    public SaleProduct() {
        initComponents();
        jLabel14.setVisible(false);
        jLabel8.setVisible(false);
        
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        tbxsearch.setVisible(false);
        String voc=vc.checkVoucherNo();
        int voci=Integer.parseInt(voc);
        lvlvoucherno.setText(String.valueOf(voci+1));
        model= (DefaultTableModel) tblVoucher.getModel();
        
        AutoSuggestor autoSuggestor = new AutoSuggestor(tbxsearch1, this, pro.searchProductInfoAll(), Color.WHITE.brighter(), Color.BLUE, Color.RED, 0.75f);
        AutoSuggestor autoSuggestor2 = new AutoSuggestor(tbxSearchMob, this, vc.searchCustomerByPhone(), Color.WHITE.brighter(), Color.BLUE, Color.RED, 0.75f);
    }
    public SaleProduct(String user) {
        initComponents();
        tbxsearch.setVisible(false);
        jLabel8.setVisible(false);
        jLabel14.setVisible(false);
        jLabel12.setVisible(false);
        jLabel13.setVisible(false);
        String voc=vc.checkVoucherNo();
        int voci=Integer.parseInt(voc);
        lvlvoucherno.setText(String.valueOf(voci+1));
        lvlusernameshow.setText(user);
        
        model= (DefaultTableModel) tblVoucher.getModel();
        
        AutoSuggestor autoSuggestor = new AutoSuggestor(tbxsearch1, this, pro.searchProductInfoAll(), Color.WHITE.brighter(), Color.BLUE, Color.RED, 0.75f);
        AutoSuggestor autoSuggestor2 = new AutoSuggestor(tbxSearchMob, this, vc.searchCustomerByPhone(), Color.WHITE.brighter(), Color.BLUE, Color.RED, 0.75f);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lvlusernameshow = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVoucher = new javax.swing.JTable();
        tbxsearch = new javax.swing.JTextField();
        tbxsearch1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lvlqu = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lvlcname = new javax.swing.JLabel();
        lvlprice = new javax.swing.JLabel();
        tbxquantity = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lvlquantity = new javax.swing.JLabel();
        lvlvoucherno = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnclrrow = new javax.swing.JButton();
        btnclrrow1 = new javax.swing.JButton();
        btnFinaVoucherl = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lvlTotalprice = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        tbxCustoname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tbxcustoaddress = new javax.swing.JTextField();
        tbxSearchMob = new javax.swing.JTextField();
        btnfatch = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnclrrow2 = new javax.swing.JButton();
        lvlproname = new javax.swing.JLabel();
        lvlcname2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        tbxPaid = new javax.swing.JTextField();
        btncpyprice = new javax.swing.JButton();
        tbxDiscount = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lvlTotalprice1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(204, 255, 102));
        jLabel1.setText("USER");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, 50, -1));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Delete Selected Row");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 130, -1));

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Copy");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 400, 50, -1));

        lvlusernameshow.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lvlusernameshow, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, 90, 20));

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Log out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 40, 80, 20));

        btnback.setBackground(new java.awt.Color(51, 51, 51));
        btnback.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnback.setForeground(new java.awt.Color(255, 255, 255));
        btnback.setText("Back");
        btnback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnbackMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnbackMouseReleased(evt);
            }
        });
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel1.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        tblVoucher.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Id", "Name", "Quantaty", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVoucher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVoucherMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVoucher);
        if (tblVoucher.getColumnModel().getColumnCount() > 0) {
            tblVoucher.getColumnModel().getColumn(0).setResizable(false);
            tblVoucher.getColumnModel().getColumn(1).setResizable(false);
            tblVoucher.getColumnModel().getColumn(2).setResizable(false);
            tblVoucher.getColumnModel().getColumn(3).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 1080, 130));

        tbxsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbxsearchKeyReleased(evt);
            }
        });
        jPanel1.add(tbxsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 100, 30));

        tbxsearch1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        tbxsearch1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                tbxsearch1ComponentAdded(evt);
            }
        });
        tbxsearch1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbxsearch1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbxsearch1MouseEntered(evt);
            }
        });
        tbxsearch1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tbxsearch1PropertyChange(evt);
            }
        });
        tbxsearch1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbxsearch1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbxsearch1KeyReleased(evt);
            }
        });
        jPanel1.add(tbxsearch1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 220, 30));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Details");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 70, 30));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Available :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 70, 20));

        lvlqu.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lvlqu.setForeground(new java.awt.Color(255, 255, 255));
        lvlqu.setText("Quantity :");
        jPanel1.add(lvlqu, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 60, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Price :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 40, 20));

        lvlcname.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lvlcname.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lvlcname, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, 150, 20));

        lvlprice.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lvlprice.setForeground(new java.awt.Color(255, 255, 255));
        lvlprice.setMaximumSize(new java.awt.Dimension(32, 15));
        lvlprice.setMinimumSize(new java.awt.Dimension(32, 15));
        jPanel1.add(lvlprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 60, 20));

        tbxquantity.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jPanel1.add(tbxquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 80, -1));

        jButton3.setBackground(new java.awt.Color(51, 51, 51));
        jButton3.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 150, 70, 20));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Company :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 70, 20));

        lvlquantity.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lvlquantity.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lvlquantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 50, 20));

        lvlvoucherno.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        lvlvoucherno.setForeground(new java.awt.Color(255, 255, 255));
        lvlvoucherno.setMaximumSize(new java.awt.Dimension(32, 15));
        lvlvoucherno.setMinimumSize(new java.awt.Dimension(32, 15));
        jPanel1.add(lvlvoucherno, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 150, 80, 20));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 0));
        jLabel7.setText("Voucher No.");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 150, 80, 20));

        btnclrrow.setBackground(new java.awt.Color(51, 51, 51));
        btnclrrow.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnclrrow.setForeground(new java.awt.Color(255, 255, 255));
        btnclrrow.setText("Exit");
        btnclrrow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnclrrowMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnclrrowMouseReleased(evt);
            }
        });
        btnclrrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclrrowActionPerformed(evt);
            }
        });
        jPanel1.add(btnclrrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 130, -1));

        btnclrrow1.setBackground(new java.awt.Color(51, 51, 51));
        btnclrrow1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnclrrow1.setForeground(new java.awt.Color(255, 255, 255));
        btnclrrow1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PrintAndDesign/remove row.png"))); // NOI18N
        btnclrrow1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 102, 102), null, null));
        btnclrrow1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnclrrow1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnclrrow1MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnclrrow1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnclrrow1MouseReleased(evt);
            }
        });
        btnclrrow1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclrrow1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnclrrow1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 40, -1));

        btnFinaVoucherl.setBackground(new java.awt.Color(51, 51, 51));
        btnFinaVoucherl.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnFinaVoucherl.setForeground(new java.awt.Color(255, 255, 255));
        btnFinaVoucherl.setText("Make voucher");
        btnFinaVoucherl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnFinaVoucherlMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnFinaVoucherlMouseReleased(evt);
            }
        });
        btnFinaVoucherl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinaVoucherlActionPerformed(evt);
            }
        });
        jPanel1.add(btnFinaVoucherl, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 470, 130, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Information");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, 70, -1));

        lvlTotalprice.setBackground(new java.awt.Color(255, 255, 255));
        lvlTotalprice.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lvlTotalprice.setForeground(new java.awt.Color(255, 255, 255));
        lvlTotalprice.setText("0.0");
        lvlTotalprice.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(lvlTotalprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 330, 130, 20));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 350, 140, 10));

        tbxCustoname.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        tbxCustoname.setText("Customer Name");
        tbxCustoname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbxCustonameMouseClicked(evt);
            }
        });
        jPanel1.add(tbxCustoname, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 210, -1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total Payable :");
        jLabel9.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 390, 100, 20));

        tbxcustoaddress.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        tbxcustoaddress.setText("Full Address");
        tbxcustoaddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbxcustoaddressMouseClicked(evt);
            }
        });
        jPanel1.add(tbxcustoaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 330, -1));

        tbxSearchMob.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        tbxSearchMob.setText("Phone No.");
        tbxSearchMob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbxSearchMobMouseClicked(evt);
            }
        });
        jPanel1.add(tbxSearchMob, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 160, -1));

        btnfatch.setBackground(new java.awt.Color(51, 51, 51));
        btnfatch.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnfatch.setForeground(new java.awt.Color(255, 255, 0));
        btnfatch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PrintAndDesign/depositphotos_4587033-stock-photo-data-sear.png"))); // NOI18N
        btnfatch.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 102, 102), null, null));
        btnfatch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnfatchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnfatchMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnfatchMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnfatchMouseReleased(evt);
            }
        });
        btnfatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfatchActionPerformed(evt);
            }
        });
        jPanel1.add(btnfatch, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 390, 30, 30));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Customer");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 70, -1));

        btnclrrow2.setBackground(new java.awt.Color(51, 51, 51));
        btnclrrow2.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnclrrow2.setForeground(new java.awt.Color(255, 255, 255));
        btnclrrow2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PrintAndDesign/deselect .png"))); // NOI18N
        btnclrrow2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 102, 102), null, null));
        btnclrrow2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnclrrow2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnclrrow2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnclrrow2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnclrrow2MouseReleased(evt);
            }
        });
        btnclrrow2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnclrrow2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnclrrow2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 30, -1));

        lvlproname.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        lvlproname.setForeground(new java.awt.Color(255, 204, 204));
        jPanel1.add(lvlproname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 240, 20));

        lvlcname2.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lvlcname2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lvlcname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 170, 20));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Total Price :");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 330, 90, -1));

        tbxPaid.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        tbxPaid.setText("0.0");
        jPanel1.add(tbxPaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 420, 130, -1));

        btncpyprice.setBackground(new java.awt.Color(51, 51, 51));
        btncpyprice.setForeground(new java.awt.Color(255, 255, 255));
        btncpyprice.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PrintAndDesign/indexcpy1.png"))); // NOI18N
        btncpyprice.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 102, 102), null, null));
        btncpyprice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btncpypriceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btncpypriceMouseExited(evt);
            }
        });
        btncpyprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncpypriceActionPerformed(evt);
            }
        });
        jPanel1.add(btncpyprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 420, 30, 30));

        tbxDiscount.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        tbxDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbxDiscountActionPerformed(evt);
            }
        });
        tbxDiscount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbxDiscountKeyReleased(evt);
            }
        });
        jPanel1.add(tbxDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 360, 70, -1));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Clear Selection");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 100, -1));

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Fetch Data");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 100, -1));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, 470, 120));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255)));
        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 560, 80));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PrintAndDesign/LOGOHeader.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 160, 60));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("%");
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 360, 30, 20));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Paid :");
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 420, 50, 20));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 410, 140, 10));

        lvlTotalprice1.setBackground(new java.awt.Color(255, 255, 255));
        lvlTotalprice1.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lvlTotalprice1.setForeground(new java.awt.Color(255, 255, 255));
        lvlTotalprice1.setText("0.0");
        lvlTotalprice1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(lvlTotalprice1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 390, 130, 20));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Discount :");
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 360, 70, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Main_LogIn().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnbackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbackMousePressed

    private void btnbackMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnbackMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbackMouseReleased

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        String u=lvlusernameshow.getText();
        new AfterLogIn(u).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void tbxsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbxsearchKeyReleased
        
    }//GEN-LAST:event_tbxsearchKeyReleased

    private void tbxsearch1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbxsearch1KeyReleased
        
    }//GEN-LAST:event_tbxsearch1KeyReleased

    private void tbxsearch1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbxsearch1KeyPressed
//        String idsearch="";
//        if (evt.getKeyCode()==java.awt.event.KeyEvent.VK_ENTER){
//            String k=tbxsearch1.getText();  
//            String[] aux = k.split("_",0);
//            for(int i=0;i<aux.length;i++){
//                if (aux.length==i+1) {
//                    idsearch=aux[i];
//                }
//            }
//            
//        }
//        tbxsearch.setText(idsearch);
    }//GEN-LAST:event_tbxsearch1KeyPressed

    private void tbxsearch1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbxsearch1MouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tbxsearch1MouseEntered

    private void tbxsearch1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tbxsearch1PropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_tbxsearch1PropertyChange

    private void tbxsearch1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_tbxsearch1ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tbxsearch1ComponentAdded

    private void tbxsearch1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbxsearch1MouseClicked
        
    }//GEN-LAST:event_tbxsearch1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (!tbxsearch1.getText().equals("")) {
            String idsearch = "";
            String k = tbxsearch1.getText();
            String[] aux = k.split("_", 0);
            for (int i = 0; i < aux.length; i++) {
                if (aux.length == i + 1) {
                    idsearch = aux[i];
                }
            }
            tbxsearch.setText(idsearch);
        }
        ArrayList<ProductInfo> p = new ArrayList();
        p = pro.searchProductForSale(tbxsearch.getText());
        try {
            lvlproname.setText(p.get(0).getPname());
            lvlcname.setText(p.get(0).getCname());
            String qu = String.valueOf(p.get(0).getQuqntity());
            lvlquantity.setText(qu);
            String cost = p.get(0).getCost();
            String profit = p.get(0).getProfit();
            double costd = Double.parseDouble(cost);
            double profitd = Double.parseDouble(profit);
            double price = costd + (costd * (profitd / 100));
            lvlprice.setText(String.valueOf(price));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Product id invalid", "invalid", JOptionPane.ERROR_MESSAGE);
        }
        tbxsearch1.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if (!tbxquantity.getText().equals("") && !lvlquantity.getText().equals("")) {

            String q = tbxquantity.getText();
            String avq = lvlquantity.getText();
            int qi = Integer.parseInt(q);
            int avqi = Integer.parseInt(avq);
            double unitPrice = Double.parseDouble(lvlprice.getText());
            double price = qi * unitPrice;
            if (avqi >= qi) {
                try {
                    int selectedRowIndex = tblVoucher.getSelectedRow();
                    model.removeRow(selectedRowIndex);
                    tblselect = "";
                } catch (Exception e) {

                }
                Object[] row = {tbxsearch.getText(), lvlproname.getText(), qi, price};
                model.addRow(row);
                tbxsearch.setText("");
                lvlproname.setText("");
                tbxquantity.setText("");
                lvlquantity.setText("");
                lvlprice.setText("");
                lvlcname.setText("");
                int i = model.getRowCount();
                double priceintable = 0;
                String pricetbl[] = new String[i];
                for (int x = 0; x < i; x++) {
                    pricetbl[x] = model.getValueAt(x, 3).toString();
                    double p = Double.parseDouble(pricetbl[x]);
                    priceintable = priceintable + p;
                }
                lvlTotalprice.setText(String.valueOf(priceintable));
                if(tbxDiscount.getText().equals("")){
                    lvlTotalprice1.setText(lvlTotalprice.getText());
                }else
                {
                    double dsc=Double.parseDouble(tbxDiscount.getText());
                    lvlTotalprice1.setText(String.valueOf(priceintable-(priceintable*(dsc/100))));
                }
            } else {
                JOptionPane.showMessageDialog(this, "Invalid Quantity", "invalid", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Some Fields Empty", "invalid", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnclrrowMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclrrowMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnclrrowMousePressed

    private void btnclrrowMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclrrowMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnclrrowMouseReleased

    private void btnclrrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclrrowActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnclrrowActionPerformed

    private void btnclrrow1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclrrow1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnclrrow1MousePressed

    private void btnclrrow1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclrrow1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnclrrow1MouseReleased

    private void btnclrrow1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclrrow1ActionPerformed
        tbxDiscount.setText("");
        try {
            int selectedRowIndex = tblVoucher.getSelectedRow();
            model.removeRow(selectedRowIndex);
            tblselect="";
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please Select 1 Row", "Try Again", JOptionPane.ERROR_MESSAGE);
        }
        int i=model.getRowCount();
        double priceintable=0;
                String pricetbl[]=new String[i];
                        for(int x=0;x<i;x++){
                        pricetbl[x]=model.getValueAt(x, 3).toString();
                        double p=Double.parseDouble(pricetbl[x]);
                        priceintable=priceintable+p;
                        }
                        lvlTotalprice.setText(String.valueOf(priceintable));
                        if(tbxDiscount.getText().equals("")){
                    lvlTotalprice1.setText(lvlTotalprice.getText());
                }else
                {
                    double dsc=Double.parseDouble(tbxDiscount.getText());
                    lvlTotalprice1.setText(String.valueOf(priceintable-(priceintable*(dsc/100))));
                }
    }//GEN-LAST:event_btnclrrow1ActionPerformed

    private void btnFinaVoucherlMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinaVoucherlMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFinaVoucherlMousePressed

    private void btnFinaVoucherlMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFinaVoucherlMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnFinaVoucherlMouseReleased

    private void btnFinaVoucherlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinaVoucherlActionPerformed
        double x = 0;
        double y = 0;
        try {
            x = Double.parseDouble(lvlTotalprice.getText());
            y = Double.parseDouble(tbxPaid.getText());
        } catch (Exception e) {
        }
        int dialogResult = JOptionPane.showConfirmDialog(this, "Are You Sure The Amount of " + y + " Was Paid?", "Confirmation!", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            if (x > 0 && y >= 0 && !tbxSearchMob.getText().equals("") && !tbxSearchMob.getText().equals("Phone No.") && !tbxCustoname.getText().equals("") && !tbxcustoaddress.getText().equals("")) {
                int rowcount = model.getRowCount();
                String pidarray[] = new String[rowcount];
                String quantityarray[] = new String[rowcount];
                for (int i = 0; i < rowcount; i++) {
                    pidarray[i] = model.getValueAt(i, 0).toString();
                    quantityarray[i] = model.getValueAt(i, 2).toString();
                    vd.InsartVoucherDetails(pidarray[i], quantityarray[i], lvlvoucherno.getText());
                    String dbProQuantity = pro.productQuantityCheck(pidarray[i]);
                    int dbProQuantityint = Integer.parseInt(dbProQuantity);
                    int quantsub = Integer.parseInt(quantityarray[i]);
                    int qnew = dbProQuantityint - quantsub;
                    pro.updateProQuanAfterSale(pidarray[i], String.valueOf(qnew));
                }
                vc.InsartVoucherCustomer(tbxCustoname.getText(), tbxSearchMob.getText(), lvlTotalprice1.getText(), tbxPaid.getText(), lvlusernameshow.getText(),tbxDiscount.getText());
                pi.insertPaymentIns(lvlvoucherno.getText(),1, tbxPaid.getText());
                if (customerT == "new") {
                    cus.customerInsart(tbxCustoname.getText(), tbxSearchMob.getText(), tbxcustoaddress.getText());
                }
                JOptionPane.showMessageDialog(this, "Information Successfully Recoreded", "Done!", JOptionPane.INFORMATION_MESSAGE);
                
                String u = lvlusernameshow.getText();
                new SearchSaleDate(u,lvlvoucherno.getText()).setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Something is wrong", "invalid", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnFinaVoucherlActionPerformed

    private void tblVoucherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVoucherMouseClicked
        int selectedRowIndex = tblVoucher.getSelectedRow();
        if (selectedRowIndex >= 0) {
            tbxsearch.setText(model.getValueAt(selectedRowIndex, 0).toString());
            ArrayList<ProductInfo> p = new ArrayList();
            p = pro.searchProductForSale(tbxsearch.getText());
            try {
                lvlproname.setText(p.get(0).getPname());
                lvlcname.setText(p.get(0).getCname());
                int q = p.get(0).getQuqntity();
                String qu = String.valueOf(q);
                lvlquantity.setText(qu);
                String cost = p.get(0).getCost();
                String profit = p.get(0).getProfit();
                double costd = Double.parseDouble(cost);
                double profitd = Double.parseDouble(profit);
                double price = costd + (costd * (profitd / 100));
                lvlprice.setText(String.valueOf(price));

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Product id invalid", "invalid", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_tblVoucherMouseClicked

    private void btnfatchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnfatchMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnfatchMousePressed

    private void btnfatchMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnfatchMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnfatchMouseReleased

    private void btnfatchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfatchActionPerformed
        try {
            ArrayList<CustomerInfo> c = new ArrayList();
            c = cus.searchCustomerbyphone(tbxSearchMob.getText().substring(0, 11));

            tbxCustoname.setText(c.get(0).getCustomer_name());
            tbxcustoaddress.setText(c.get(0).getAddress());
            //tbxSearchMob.setText(c.get(0).getPhone());
            customerT="known";
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Seems New Contact No.", "Unknown contact", JOptionPane.ERROR_MESSAGE);
            customerT="new";
        }
    }//GEN-LAST:event_btnfatchActionPerformed

    private void btnclrrow2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclrrow2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnclrrow2MousePressed

    private void btnclrrow2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclrrow2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnclrrow2MouseReleased

    private void btnclrrow2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnclrrow2ActionPerformed
        tblVoucher.getSelectionModel().clearSelection();
    }//GEN-LAST:event_btnclrrow2ActionPerformed

    private void tbxSearchMobMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbxSearchMobMouseClicked
        tbxSearchMob.setText("");
        tbxCustoname.setText("");
        tbxcustoaddress.setText("");
    }//GEN-LAST:event_tbxSearchMobMouseClicked

    private void tbxCustonameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbxCustonameMouseClicked
        tbxCustoname.setText("");
    }//GEN-LAST:event_tbxCustonameMouseClicked

    private void tbxcustoaddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbxcustoaddressMouseClicked
        tbxcustoaddress.setText("");
    }//GEN-LAST:event_tbxcustoaddressMouseClicked

    private void btncpypriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncpypriceActionPerformed
        tbxPaid.setText(lvlTotalprice1.getText());
    }//GEN-LAST:event_btncpypriceActionPerformed

    private void btnfatchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnfatchMouseEntered
        btnfatch.setBackground(new Color(255,255,0).brighter());
        jLabel14.setOpaque(true);
        jLabel14.setBackground(Color.WHITE);
        jLabel14.setVisible(true);
    }//GEN-LAST:event_btnfatchMouseEntered

    private void btnfatchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnfatchMouseExited
        btnfatch.setBackground(new Color(51,51,51).brighter());
        jLabel14.setVisible(false);
    }//GEN-LAST:event_btnfatchMouseExited

    private void btncpypriceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncpypriceMouseEntered
        btncpyprice.setBackground(new Color(255,255,0).brighter());
        jLabel12.setOpaque(true);
        jLabel12.setBackground(Color.WHITE);
        jLabel12.setVisible(true);
    }//GEN-LAST:event_btncpypriceMouseEntered

    private void btncpypriceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncpypriceMouseExited
        btncpyprice.setBackground(new Color(51,51,51).brighter());
        jLabel12.setVisible(false);
    }//GEN-LAST:event_btncpypriceMouseExited

    private void btnclrrow2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclrrow2MouseEntered
        btnclrrow2.setBackground(new Color(255,255,0).brighter());
        jLabel8.setOpaque(true);
        jLabel8.setBackground(Color.WHITE);
        jLabel8.setVisible(true);
    }//GEN-LAST:event_btnclrrow2MouseEntered

    private void btnclrrow2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclrrow2MouseExited
        btnclrrow2.setBackground(new Color(51,51,51).brighter());
        jLabel8.setVisible(false);
    }//GEN-LAST:event_btnclrrow2MouseExited

    private void btnclrrow1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclrrow1MouseEntered
        btnclrrow1.setBackground(new Color(255,255,0).brighter());
        jLabel13.setOpaque(true);
        jLabel13.setBackground(Color.WHITE);
        jLabel13.setVisible(true);
    }//GEN-LAST:event_btnclrrow1MouseEntered

    private void btnclrrow1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnclrrow1MouseExited
        btnclrrow1.setBackground(new Color(51,51,51).brighter());
        jLabel13.setVisible(false);
    }//GEN-LAST:event_btnclrrow1MouseExited

    private void tbxDiscountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbxDiscountKeyReleased
        try {
            int i = model.getRowCount();
            if (i > 0) {
                double priceintable = 0;
                String pricetbl[] = new String[i];
                for (int x = 0; x < i; x++) {
                    pricetbl[x] = model.getValueAt(x, 3).toString();
                    double p = Double.parseDouble(pricetbl[x]);
                    priceintable = priceintable + p;
                }

                double descount = Double.parseDouble(tbxDiscount.getText());
                double p = (priceintable - (priceintable * (descount / 100)));
                lvlTotalprice1.setText(String.valueOf(p));
            } else {
            }
        } catch (Exception e) {
            int i = model.getRowCount();
            double priceintable = 0;
                String pricetbl[] = new String[i];
                for (int x = 0; x < i; x++) {
                    pricetbl[x] = model.getValueAt(x, 3).toString();
                    double p = Double.parseDouble(pricetbl[x]);
                    priceintable = priceintable + p;
                }
                lvlTotalprice1.setText(String.valueOf(priceintable));
        }
    }//GEN-LAST:event_tbxDiscountKeyReleased

    private void tbxDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbxDiscountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbxDiscountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaleProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaleProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaleProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaleProduct.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaleProduct().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinaVoucherl;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnclrrow;
    private javax.swing.JButton btnclrrow1;
    private javax.swing.JButton btnclrrow2;
    private javax.swing.JButton btncpyprice;
    private javax.swing.JButton btnfatch;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lvlTotalprice;
    private javax.swing.JLabel lvlTotalprice1;
    private javax.swing.JLabel lvlcname;
    private javax.swing.JLabel lvlcname2;
    private javax.swing.JLabel lvlprice;
    private javax.swing.JLabel lvlproname;
    private javax.swing.JLabel lvlqu;
    private javax.swing.JLabel lvlquantity;
    private javax.swing.JLabel lvlusernameshow;
    private javax.swing.JLabel lvlvoucherno;
    private javax.swing.JTable tblVoucher;
    private javax.swing.JTextField tbxCustoname;
    private javax.swing.JTextField tbxDiscount;
    private javax.swing.JTextField tbxPaid;
    private javax.swing.JTextField tbxSearchMob;
    private javax.swing.JTextField tbxcustoaddress;
    private javax.swing.JTextField tbxquantity;
    private javax.swing.JTextField tbxsearch;
    private javax.swing.JTextField tbxsearch1;
    // End of variables declaration//GEN-END:variables
}
