package Gui;

import DBmanage.DBconnPaymentInstallments;
import DBmanage.DBconnProduct;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import MainPackeg.ProductInfo;
import MainPackeg.VoucherCustomer;
import DBmanage.DBconnVoucherCustomer;
import DBmanage.DBconnVoucherDetails;
import DBmanage.DBconnVoucherDetails;
import MainPackeg.VoucherDetails;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.FileOutputStream;
import java.text.DecimalFormat;
import javafx.scene.text.Text;
import javafx.scene.text.TextAlignment;
import javax.swing.JOptionPane;

/**
 *
 * @author romio-pc
 */
public class SearchSaleDate extends javax.swing.JFrame {

    DefaultTableModel model1;
    String SelectedRowvoucherNumber = "";
    DBconnProduct pro = new DBconnProduct();
    DBconnVoucherCustomer vc = new DBconnVoucherCustomer();
    DBconnVoucherDetails vd = new DBconnVoucherDetails();
    DBconnPaymentInstallments pi = new DBconnPaymentInstallments();

    /**
     * Creates new form SearchSaleDate
     */
    public SearchSaleDate() {
        initComponents();
        jDateChooser1.setEnabled(false);
        jDateChooser2.setEnabled(false);
        btnSearch.setEnabled(false);
        tbxVNO.setEnabled(false);
        model1 = (DefaultTableModel) tblVoucherCustomer.getModel();
    }

    public SearchSaleDate(String user, String vn) {
        initComponents();
        jDateChooser1.setEnabled(false);
        jDateChooser2.setEnabled(false);
        chboxdueOnly.setEnabled(false);
        btnSearch.setEnabled(false);
        tbxVNO.setEnabled(false);
        lvlusernameshow.setText(user);
        model1 = (DefaultTableModel) tblVoucherCustomer.getModel();
        ArrayList<VoucherCustomer> list = new ArrayList();
        list = vc.searchByVoucherNo(vn);
        model1.setRowCount(0);
        for (int i = 0; i < list.size(); i++) {
            Object[] row = {list.get(i).getvNo(), list.get(i).getCuName(), list.get(i).getPhone(), list.get(i).getPayable(), list.get(i).getPaid(), list.get(i).getUser(), list.get(i).getTime(), list.get(i).getDiscount()};
            model1.addRow(row);
        }
        int i = model1.getRowCount();
        double totalPayable = 0;
        double totalPaid = 0;
        String paid[] = new String[i];
        String payable[] = new String[i];
        for (int x = 0; x < i; x++) {
            payable[x] = model1.getValueAt(x, 3).toString();
            paid[x] = model1.getValueAt(x, 4).toString();
            double pbl = Double.parseDouble(payable[x]);
            totalPayable = totalPayable + pbl;
            double pd = Double.parseDouble(paid[x]);
            totalPaid = totalPaid + pd;
        }
        lvltpable.setText(String.valueOf(totalPayable));
        lvltpaid.setText(String.valueOf(totalPaid));
        lvldue.setText(String.valueOf((totalPayable - totalPaid)));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVoucherCustomer = new javax.swing.JTable();
        btnLast5sale = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lvlusernameshow = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        ChboxVoucher = new javax.swing.JCheckBox();
        Chboxdate = new javax.swing.JCheckBox();
        jSeparator1 = new javax.swing.JSeparator();
        tbxVNO = new javax.swing.JTextField();
        btnPrintVoucher = new javax.swing.JButton();
        btnVoucherShow = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lvltpable = new javax.swing.JLabel();
        lvltpaid = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lvldue = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        chboxdueOnly = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        tbxdu = new javax.swing.JTextField();
        btnUpPayment = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnBack1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 160, -1));
        jPanel1.add(jDateChooser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 150, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("To");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("From");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        tblVoucherCustomer.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        tblVoucherCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Voucher No.", "Customer Name", "Contact No.", "Payable", "Paid", "Reference", "Date Time", "Discount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVoucherCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVoucherCustomerMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblVoucherCustomer);
        if (tblVoucherCustomer.getColumnModel().getColumnCount() > 0) {
            tblVoucherCustomer.getColumnModel().getColumn(0).setResizable(false);
            tblVoucherCustomer.getColumnModel().getColumn(1).setResizable(false);
            tblVoucherCustomer.getColumnModel().getColumn(2).setResizable(false);
            tblVoucherCustomer.getColumnModel().getColumn(3).setResizable(false);
            tblVoucherCustomer.getColumnModel().getColumn(4).setResizable(false);
            tblVoucherCustomer.getColumnModel().getColumn(5).setResizable(false);
            tblVoucherCustomer.getColumnModel().getColumn(6).setResizable(false);
            tblVoucherCustomer.getColumnModel().getColumn(7).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 1080, 170));

        btnLast5sale.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnLast5sale.setText("Last 5 Sales");
        btnLast5sale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLast5saleActionPerformed(evt);
            }
        });
        jPanel1.add(btnLast5sale, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 150, 120, -1));

        jLabel6.setForeground(new java.awt.Color(204, 255, 102));
        jLabel6.setText("USER");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 20, 50, -1));

        lvlusernameshow.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lvlusernameshow, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 20, 90, 20));

        jButton5.setText("Log out");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 50, 80, -1));

        btnBack.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        ChboxVoucher.setBackground(new java.awt.Color(0, 102, 102));
        ChboxVoucher.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        ChboxVoucher.setForeground(new java.awt.Color(255, 255, 255));
        ChboxVoucher.setText("Voucher");
        ChboxVoucher.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChboxVoucherMouseClicked(evt);
            }
        });
        jPanel1.add(ChboxVoucher, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 70, 30));

        Chboxdate.setBackground(new java.awt.Color(0, 102, 102));
        Chboxdate.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        Chboxdate.setForeground(new java.awt.Color(255, 255, 255));
        Chboxdate.setText("Date Wise");
        Chboxdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ChboxdateMouseClicked(evt);
            }
        });
        jPanel1.add(Chboxdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 90, 30));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 630, 10));

        tbxVNO.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        tbxVNO.setText("Enter Voucher No Here");
        tbxVNO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbxVNOMouseClicked(evt);
            }
        });
        jPanel1.add(tbxVNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 160, -1));

        btnPrintVoucher.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnPrintVoucher.setText("Print Voucher");
        btnPrintVoucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintVoucherActionPerformed(evt);
            }
        });
        jPanel1.add(btnPrintVoucher, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 140, -1));

        btnVoucherShow.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnVoucherShow.setText("Full Voucher In Details");
        btnVoucherShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoucherShowActionPerformed(evt);
            }
        });
        jPanel1.add(btnVoucherShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 160, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 3, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total Payable :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, 100, 20));

        lvltpable.setFont(new java.awt.Font("Century Gothic", 3, 11)); // NOI18N
        lvltpable.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lvltpable, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 370, 140, 20));

        lvltpaid.setFont(new java.awt.Font("Century Gothic", 3, 11)); // NOI18N
        lvltpaid.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lvltpaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 400, 140, 20));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 3, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Total Paid  :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, 80, 20));

        lvldue.setFont(new java.awt.Font("Century Gothic", 3, 11)); // NOI18N
        lvldue.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lvldue, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 430, 140, 20));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 3, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Total Due :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, 80, 20));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSearch.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel2.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, -1, 60));

        chboxdueOnly.setBackground(new java.awt.Color(0, 102, 102));
        chboxdueOnly.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        chboxdueOnly.setForeground(new java.awt.Color(255, 255, 255));
        chboxdueOnly.setText("Due Only");
        jPanel2.add(chboxdueOnly, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 90, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 770, 90));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbxdu.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        tbxdu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbxduMouseClicked(evt);
            }
        });
        tbxdu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbxduActionPerformed(evt);
            }
        });
        jPanel3.add(tbxdu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 130, -1));

        btnUpPayment.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnUpPayment.setText("Add Payment");
        btnUpPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpPaymentActionPerformed(evt);
            }
        });
        jPanel3.add(btnUpPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 130, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 102));
        jLabel1.setText(" Repayable Amount Of Selected Voucher :");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 270, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 320, 90));

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 370, 320, 90));

        btnBack1.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        btnBack1.setText("Exit");
        btnBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 470, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PrintAndDesign/LOGOHeader.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 160, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        SelectedRowvoucherNumber = "";
        tbxdu.setText("");
        if (Chboxdate.isSelected()) {
            
            try {
                DateFormat updt = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
                DateFormat updt2 = new SimpleDateFormat("yyyy-MM-dd 23:59:59");

                String s1 = updt.format(jDateChooser1.getDate());
                String s2 = updt2.format(jDateChooser2.getDate());

                ArrayList<VoucherCustomer> p = new ArrayList();
                if (chboxdueOnly.isSelected()) {
                    p = vc.searchVoucherBetweenDateDueOnly(s1, s2);
                } else {
                    p = vc.searchVoucherBetweenDate(s1, s2);
                }
                model1.setRowCount(0);
                for (int i = 0; i < p.size(); i++) {
                    Object[] row = {p.get(i).getvNo(), p.get(i).getCuName(), p.get(i).getPhone(), p.get(i).getPayable(), p.get(i).getPaid(), p.get(i).getUser(), p.get(i).getTime(), p.get(i).getDiscount()};
                    model1.addRow(row);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Input Valid Date", "Invalid Input", JOptionPane.ERROR_MESSAGE);
            }
        } else if (ChboxVoucher.isSelected()) {
            
            ArrayList<VoucherCustomer> list = new ArrayList();
            list = vc.searchByVoucherNo(tbxVNO.getText());
            model1.setRowCount(0);
            for (int i = 0; i < list.size(); i++) {
                Object[] row = {list.get(i).getvNo(), list.get(i).getCuName(), list.get(i).getPhone(), list.get(i).getPayable(), list.get(i).getPaid(), list.get(i).getUser(), list.get(i).getTime(), list.get(i).getDiscount()};
                model1.addRow(row);
            }

        } else {
            JOptionPane.showMessageDialog(this, "Nothing Is Chaked", "Check Required", JOptionPane.ERROR_MESSAGE);
        }
        int i = model1.getRowCount();
        double totalPayable = 0;
        double totalPaid = 0;
        String paid[] = new String[i];
        String payable[] = new String[i];
        for (int x = 0; x < i; x++) {
            payable[x] = model1.getValueAt(x, 3).toString();
            paid[x] = model1.getValueAt(x, 4).toString();
            double pbl = Double.parseDouble(payable[x]);
            totalPayable = totalPayable + pbl;
            double pd = Double.parseDouble(paid[x]);
            totalPaid = totalPaid + pd;
        }
        lvltpable.setText(String.valueOf(totalPayable));
        lvltpaid.setText(String.valueOf(totalPaid));
        lvldue.setText(String.valueOf((totalPayable - totalPaid)));

    }//GEN-LAST:event_btnSearchActionPerformed

    private void tblVoucherCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVoucherCustomerMouseClicked
        try {
            int selectedrowindex = tblVoucherCustomer.getSelectedRow();
            SelectedRowvoucherNumber = model1.getValueAt(selectedrowindex, 0).toString();
            Double pbl = Double.parseDouble(model1.getValueAt(selectedrowindex, 3).toString());
            Double pd = Double.parseDouble(model1.getValueAt(selectedrowindex, 4).toString());
            tbxdu.setText(String.valueOf(pbl - pd));
        } catch (Exception e) {
        }

    }//GEN-LAST:event_tblVoucherCustomerMouseClicked

    private void btnLast5saleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLast5saleActionPerformed
        SelectedRowvoucherNumber = "";
        tbxdu.setText("");
        ArrayList<VoucherCustomer> list = new ArrayList();
        list = vc.lastFiveSales();
        model1.setRowCount(0);
        for (int i = 0; i < list.size(); i++) {
            Object[] row = {list.get(i).getvNo(), list.get(i).getCuName(), list.get(i).getPhone(), list.get(i).getPayable(), list.get(i).getPaid(), list.get(i).getUser(), list.get(i).getTime(), list.get(i).getDiscount()};
            model1.addRow(row);
        }
        int i = model1.getRowCount();
        double totalPayable = 0;
        double totalPaid = 0;
        String paid[] = new String[i];
        String payable[] = new String[i];
        for (int x = 0; x < i; x++) {
            payable[x] = model1.getValueAt(x, 3).toString();
            paid[x] = model1.getValueAt(x, 4).toString();
            double pbl = Double.parseDouble(payable[x]);
            totalPayable = totalPayable + pbl;
            double pd = Double.parseDouble(paid[x]);
            totalPaid = totalPaid + pd;
        }
        lvltpable.setText(String.valueOf(totalPayable));
        lvltpaid.setText(String.valueOf(totalPaid));
        lvldue.setText(String.valueOf((totalPayable - totalPaid)));
    }//GEN-LAST:event_btnLast5saleActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        new Main_LogIn().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        String u = lvlusernameshow.getText();
        new AfterLogIn(u).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void tbxVNOMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbxVNOMouseClicked
        tbxVNO.setText("");
    }//GEN-LAST:event_tbxVNOMouseClicked

    private void ChboxdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChboxdateMouseClicked
        chboxdueOnly.setEnabled(true);
        ChboxVoucher.setSelected(false);
        jDateChooser1.setEnabled(true);
        jDateChooser2.setEnabled(true);
        tbxVNO.setEnabled(false);
        btnSearch.setEnabled(true);
    }//GEN-LAST:event_ChboxdateMouseClicked

    private void ChboxVoucherMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ChboxVoucherMouseClicked
        chboxdueOnly.setEnabled(false);
        Chboxdate.setSelected(false);
        tbxVNO.setEnabled(true);
        jDateChooser1.setEnabled(false);
        jDateChooser2.setEnabled(false);
        btnSearch.setEnabled(true);
    }//GEN-LAST:event_ChboxVoucherMouseClicked

    private void btnPrintVoucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintVoucherActionPerformed
//        pdfprint();
        if (SelectedRowvoucherNumber != "") {
            int z = tblVoucherCustomer.getSelectedRow();
            try {
                Document doc = new Document();
                DecimalFormat format = new DecimalFormat("0.00");
                PdfWriter.getInstance(doc, new FileOutputStream("printpdf.pdf"));
                PdfPTable table = new PdfPTable(4);
                PdfPTable head = new PdfPTable(2);
                doc.open();
                Image image = Image.getInstance("logo.png");
                Image image2= Image.getInstance("OOPJAVAPROJECT.png");
                image2.scalePercent(50, 30);
                image.setAlignment(Element.ALIGN_CENTER);
                image.scaleAbsolute(300,300);
                image.setAbsolutePosition(150,300);
                image2.setAlignment(Element.ALIGN_CENTER);
                
                doc.add(image2);
                doc.add(image);
                DateFormat dateformt = new SimpleDateFormat("dd-MM-yyyy");
                Date date = new Date();
                String d = dateformt.format(date).toString();
                head.setWidthPercentage(100);
                head.setWidths(new int[]{200,50});
                head.addCell(getCell("New Shop", PdfPCell.ALIGN_LEFT,30,1));
                head.addCell(getCell("", PdfPCell.ALIGN_LEFT,14));
                head.addCell(getCell("102 Mirpur Rd, \nDhaka 1207, Bangladesh", PdfPCell.ALIGN_LEFT,14));
                head.addCell(getCell("Voucher No. " + SelectedRowvoucherNumber+"\nDate: " + d, PdfPCell.ALIGN_LEFT,14));
                doc.add(head);
                Paragraph header1 = new Paragraph("Cash Voucher", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18, Font.BOLD, BaseColor.MAGENTA));
                header1.setAlignment(Element.ALIGN_CENTER);
                doc.add(header1);
                Paragraph dotedline = new Paragraph("--------------------------------------------------------");
                dotedline.setAlignment(Element.ALIGN_CENTER);
                doc.add(dotedline);
                String custName = model1.getValueAt(z, 1).toString();
                String custPhn = model1.getValueAt(z, 2).toString();
                String soldBy = model1.getValueAt(z, 5).toString();
                head = new PdfPTable(2);
                head.setWidthPercentage(100);
                head.setWidths(new int[]{150,100});
                head.addCell(getCell("Bill To :", PdfPCell.ALIGN_LEFT,14,1));
                head.addCell(getCell("Sale :", PdfPCell.ALIGN_LEFT,14,1));
                head.addCell(getCell("Name: "+custName, PdfPCell.ALIGN_LEFT,14));
                head.addCell(getCell("Saler Name: "+soldBy, PdfPCell.ALIGN_LEFT,14));
                head.addCell(getCell("Phone: "+custPhn, PdfPCell.ALIGN_LEFT,14));
                head.addCell(getCell("Owner & Manager: Mr. Malik", PdfPCell.ALIGN_LEFT,14));
                head.addCell(getCell("-\t", PdfPCell.ALIGN_LEFT,14));
                head.addCell(getCell("Shop Phone: 01XXXXXXXXX", PdfPCell.ALIGN_LEFT,14));
                doc.add(head);
                doc.add(new Paragraph("\n"));
                table.setWidthPercentage(100);
                table.addCell(getCellPrice("Product Id",PdfPCell.ALIGN_CENTER));
                table.addCell(getCellPrice("Product Name",PdfPCell.ALIGN_CENTER));
                table.addCell(getCellPrice("Quantity",PdfPCell.ALIGN_CENTER));
                table.addCell(getCellPrice("Price",PdfPCell.ALIGN_CENTER));

                ArrayList<VoucherDetails> list = new ArrayList();
                list = vd.fullVoucherDetails(SelectedRowvoucherNumber);
                for (int i = 0; i < list.size(); i++) {
                    String id = String.valueOf(list.get(i).getPid());
                    int q = list.get(i).getQuant();
                    ArrayList<ProductInfo> list2 = new ArrayList();
                    list2 = pro.searchProductForSale(id);
                    String nam = list2.get(0).getPname();
                    String cst = list2.get(0).getCost();
                    double cost = Double.parseDouble(cst);
                    String prof = list2.get(0).getProfit();
                    double profit = Double.parseDouble(prof);
                    double price = (cost + (cost * (profit / 100)));
                    double tprice = (q * price);
                    
                    String formatted = format.format(tprice);

                    table.addCell(getCellPrice(id,PdfPCell.ALIGN_CENTER));
                    table.addCell(nam);
                    table.addCell(getCellPrice(String.valueOf(q),PdfPCell.ALIGN_CENTER));
                    table.addCell(getCellPrice(formatted, PdfPCell.ALIGN_RIGHT));
                }

                doc.add(table);


                String payable = model1.getValueAt(z, 3).toString();
                String paid = model1.getValueAt(z, 4).toString();
                String discnt = model1.getValueAt(z, 7).toString();
                Paragraph pamount = new Paragraph("Discount = " + discnt + "  %   " + "\nTotal Payable = " + payable + " BDT " + "\nTotal Paid = " + paid + " BDT");
                pamount.setAlignment(Element.ALIGN_RIGHT);
                doc.add(pamount);
                Paragraph casher = new Paragraph("\n\n\n------------------\nCasher Signature");
                casher.setAlignment(Element.ALIGN_RIGHT);
                doc.add(casher);
                Paragraph developer = new Paragraph("Developer:\nMd.Rafiul Hassan\nMob: +8801773359806", FontFactory.getFont(FontFactory.TIMES_ITALIC, 6, Font.NORMAL, BaseColor.BLUE));
                //developer.setAlignment(Element.CCITTG3_1D);
                developer.setAlignment(Element.ALIGN_BOTTOM);
                
                doc.add(developer);
                doc.close();
            } catch (Exception e) {
            }

            try {
                Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler printpdf.pdf");
            } catch (Exception e) {
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please Select A Row", "Invalid", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPrintVoucherActionPerformed
    public PdfPCell getCell(String text, int alignment,int size) {
        PdfPCell cell = new PdfPCell();
        Font normalFont = new Font(Font.FontFamily.TIMES_ROMAN, size, Font.NORMAL);
        cell.addElement(new Phrase(text, normalFont ));
        cell.setPadding(0);
        cell.setHorizontalAlignment(alignment);
        cell.setBorder(PdfPCell.NO_BORDER);
        return cell;
    }
    public PdfPCell getCellPrice(String text, int alignment) {
        PdfPCell cell = new PdfPCell(new Phrase(text));
        cell.setHorizontalAlignment(alignment);
        return cell;
    }
    public PdfPCell getCell(String text, int alignment,int size,int bold) {
        PdfPCell cell = new PdfPCell();
        Font boldFont = new Font(Font.FontFamily.TIMES_ROMAN, size, Font.BOLD);
        cell.addElement(new Phrase(text, boldFont ));
        cell.setPadding(0);
        cell.setHorizontalAlignment(alignment);
        cell.setBorder(PdfPCell.NO_BORDER);
        return cell;
    }

    
    private void btnVoucherShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoucherShowActionPerformed
        try {
            int sel = -1;
            sel = tblVoucherCustomer.getSelectedRow();
            if (sel >= 0) {
                String k = tblVoucherCustomer.getValueAt(sel, 0).toString();
                new FullVoucherShow(k).setVisible(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please Select A Row", "Invalid", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnVoucherShowActionPerformed

    private void tbxduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbxduActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbxduActionPerformed

    private void btnUpPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpPaymentActionPerformed
        int dialogResult = JOptionPane.showConfirmDialog(this, "Are You Sure The Repayable Amount of " + tbxdu.getText() + " Was Paid?", "Confirmation!", JOptionPane.YES_NO_OPTION);
        if(dialogResult==JOptionPane.YES_OPTION){
        try {
            int selectedrowindex = tblVoucherCustomer.getSelectedRow();
            Double pbl = Double.parseDouble(model1.getValueAt(selectedrowindex, 3).toString());
            Double pd = Double.parseDouble(model1.getValueAt(selectedrowindex, 4).toString());
            String vnum = model1.getValueAt(selectedrowindex, 0).toString();
            double enteredAmount = Double.parseDouble(tbxdu.getText());
            double comam = pbl - pd;
            if (pbl > pd && selectedrowindex >= 0 && comam >= enteredAmount) {
                vc.addRepayableAmount(vnum, String.valueOf(enteredAmount + pd));
                int insNum = pi.checkInstallmentNo(vnum);
                int inNum = insNum + 1;
                pi.insertPaymentIns(vnum, inNum, String.valueOf(enteredAmount));

                ArrayList<VoucherCustomer> list = new ArrayList();
                list = vc.searchByVoucherNo(vnum);
                model1.setRowCount(0);
                for (int i = 0; i < list.size(); i++) {
                    Object[] row = {list.get(i).getvNo(), list.get(i).getCuName(), list.get(i).getPhone(), list.get(i).getPayable(), list.get(i).getPaid(), list.get(i).getUser(), list.get(i).getTime(), list.get(i).getDiscount()};
                    model1.addRow(row);
                }
                lvltpable.setText(String.valueOf(pbl));
                lvltpaid.setText(String.valueOf(pd));
                lvldue.setText(String.valueOf(comam-enteredAmount));
                JOptionPane.showMessageDialog(this, "Repayable Amount Successfully Added", "Done!", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "No Repayable Amount or Over Amount", "Repayable Amount Invalid", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please Select A Row", "Invalid", JOptionPane.ERROR_MESSAGE);
        }
        }
    }//GEN-LAST:event_btnUpPaymentActionPerformed

    private void btnBack1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnBack1ActionPerformed

    private void tbxduMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbxduMouseClicked
        tbxdu.setText("");
    }//GEN-LAST:event_tbxduMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchSaleDate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchSaleDate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchSaleDate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchSaleDate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchSaleDate().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ChboxVoucher;
    private javax.swing.JCheckBox Chboxdate;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBack1;
    private javax.swing.JButton btnLast5sale;
    private javax.swing.JButton btnPrintVoucher;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpPayment;
    private javax.swing.JButton btnVoucherShow;
    private javax.swing.JCheckBox chboxdueOnly;
    private javax.swing.JButton jButton5;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lvldue;
    private javax.swing.JLabel lvltpable;
    private javax.swing.JLabel lvltpaid;
    private javax.swing.JLabel lvlusernameshow;
    private javax.swing.JTable tblVoucherCustomer;
    private javax.swing.JTextField tbxVNO;
    private javax.swing.JTextField tbxdu;
    // End of variables declaration//GEN-END:variables
}
