/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import DBmanage.*;
import javax.swing.JOptionPane;

/**
 *
 * @author romio-pc
 */
public class UserSignUp extends javax.swing.JFrame {

    String l="ff";
    DBconnUser obj = new DBconnUser();
    Main_LogIn ob=new Main_LogIn();

    public UserSignUp() {
        initComponents();
        tbxProductKey.setVisible(false);
        tbxProductKey.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tbxProductKey = new javax.swing.JTextField();
        cboxType = new javax.swing.JComboBox<>();
        tbxName = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        passbox = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        tbxMob = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        tbxAddress = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        btnLogIn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Type");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, 69, 22));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Username");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, 69, 22));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Password");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 69, 22));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("mobile no");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 69, 22));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Address");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 69, 22));

        tbxProductKey.setBackground(new java.awt.Color(102, 102, 102));
        tbxProductKey.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        tbxProductKey.setForeground(new java.awt.Color(255, 255, 255));
        tbxProductKey.setText("enter your product key here");
        tbxProductKey.setBorder(null);
        tbxProductKey.setCaretColor(new java.awt.Color(255, 255, 255));
        tbxProductKey.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbxProductKeyMouseClicked(evt);
            }
        });
        tbxProductKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbxProductKeyActionPerformed(evt);
            }
        });
        jPanel1.add(tbxProductKey, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, 210, 20));

        cboxType.setBackground(new java.awt.Color(102, 102, 102));
        cboxType.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        cboxType.setForeground(new java.awt.Color(255, 255, 255));
        cboxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Salesperson", "Admin" }));
        cboxType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxTypeActionPerformed(evt);
            }
        });
        jPanel1.add(cboxType, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 240, 220, -1));

        tbxName.setBackground(new java.awt.Color(51, 51, 51));
        tbxName.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        tbxName.setForeground(new java.awt.Color(255, 255, 255));
        tbxName.setText("Enter user name (Avoid Space)");
        tbxName.setBorder(null);
        tbxName.setCaretColor(new java.awt.Color(255, 255, 255));
        tbxName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbxNameMouseClicked(evt);
            }
        });
        tbxName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbxNameActionPerformed(evt);
            }
        });
        tbxName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbxNameKeyReleased(evt);
            }
        });
        jPanel1.add(tbxName, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, 210, 20));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, 220, 10));

        passbox.setBackground(new java.awt.Color(51, 51, 51));
        passbox.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        passbox.setForeground(new java.awt.Color(255, 255, 255));
        passbox.setText("jPasswordField1");
        passbox.setBorder(null);
        passbox.setCaretColor(new java.awt.Color(255, 255, 255));
        passbox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passboxMouseClicked(evt);
            }
        });
        passbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passboxActionPerformed(evt);
            }
        });
        jPanel1.add(passbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 140, 220, 20));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 160, 220, 10));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 190, 220, 10));

        tbxMob.setBackground(new java.awt.Color(51, 51, 51));
        tbxMob.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        tbxMob.setForeground(new java.awt.Color(255, 255, 255));
        tbxMob.setBorder(null);
        tbxMob.setCaretColor(new java.awt.Color(255, 255, 255));
        tbxMob.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbxMobMouseClicked(evt);
            }
        });
        tbxMob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbxMobActionPerformed(evt);
            }
        });
        jPanel1.add(tbxMob, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 210, 20));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, 220, 10));

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Sign Up");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 320, 80, -1));

        tbxAddress.setBackground(new java.awt.Color(51, 51, 51));
        tbxAddress.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        tbxAddress.setForeground(new java.awt.Color(255, 255, 255));
        tbxAddress.setBorder(null);
        tbxAddress.setCaretColor(new java.awt.Color(255, 255, 255));
        tbxAddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbxAddressMouseClicked(evt);
            }
        });
        tbxAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbxAddressActionPerformed(evt);
            }
        });
        jPanel1.add(tbxAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 200, 210, 20));

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 110, -1));

        btnLogIn1.setBackground(new java.awt.Color(102, 102, 102));
        btnLogIn1.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        btnLogIn1.setForeground(new java.awt.Color(255, 255, 255));
        btnLogIn1.setText("Exit");
        btnLogIn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLogIn1MouseReleased(evt);
            }
        });
        btnLogIn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogIn1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogIn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 470, 100, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("New User Sign Up Form");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, 260, 50));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 51)));
        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 320, 50));

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 110, 30, 230));

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("OR  Log IN ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 360, 200, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PrintAndDesign/LOGOHeader2.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 270, 250));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String k = "pk123";
        String pass= new String(passbox.getPassword());
        if (tbxName.getText().equals("") || pass.equals("") || tbxMob.getText().equals("") || tbxAddress.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Some Field Empty", "User Info", JOptionPane.ERROR_MESSAGE);

        } else if (cboxType.getSelectedItem().toString() == "Admin" && tbxProductKey.getText().equals(k)) {
            obj.insertUser(tbxName.getText(), pass, tbxMob.getText(), tbxAddress.getText(), cboxType.getSelectedItem() + "","yes");
            tbxName.setText("");
            pass=new String();
            tbxMob.setText("");
            tbxAddress.setText("");
            JOptionPane.showMessageDialog(this, "Successfully Signed up", "Signup Info", JOptionPane.INFORMATION_MESSAGE);
        } else if(cboxType.getSelectedItem().toString() == "Salesperson"){
            obj.insertUser(tbxName.getText(), pass, tbxMob.getText(), tbxAddress.getText(), cboxType.getSelectedItem() + "","no");
            tbxName.setText("");
            pass=new String();
            tbxMob.setText("");
            tbxAddress.setText("");
            JOptionPane.showMessageDialog(this, "Sign up request completed", "Signup Info", JOptionPane.INFORMATION_MESSAGE);
        } else if(cboxType.getSelectedItem().toString() == "Admin" && tbxProductKey.getText()!=k) {
            JOptionPane.showMessageDialog(this, "Invalid Key", "User Info", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void tbxProductKeyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbxProductKeyMouseClicked

        tbxProductKey.setText("");
    }//GEN-LAST:event_tbxProductKeyMouseClicked

    private void tbxProductKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbxProductKeyActionPerformed

    }//GEN-LAST:event_tbxProductKeyActionPerformed

    private void cboxTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxTypeActionPerformed
        if (cboxType.getSelectedItem().toString() == "Admin") {
            tbxProductKey.setVisible(true);
            tbxProductKey.setEnabled(true);
        } else {
            tbxProductKey.setEnabled(false);
            tbxProductKey.setEnabled(false);
        }
    }//GEN-LAST:event_cboxTypeActionPerformed

    private void tbxNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbxNameMouseClicked
        tbxName.setText("");
    }//GEN-LAST:event_tbxNameMouseClicked

    private void tbxNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbxNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbxNameActionPerformed

    private void passboxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passboxMouseClicked
        passbox.setText("");
    }//GEN-LAST:event_passboxMouseClicked

    private void passboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passboxActionPerformed

    private void tbxMobMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbxMobMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbxMobMouseClicked

    private void tbxMobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbxMobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbxMobActionPerformed

    private void tbxAddressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbxAddressMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbxAddressMouseClicked

    private void tbxAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbxAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbxAddressActionPerformed

    private void tbxNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbxNameKeyReleased
         if (obj.checkUserName(tbxName.getText())) {
            jButton1.setEnabled(true);
        } else {
            jButton1.setEnabled(false);
        }
    }//GEN-LAST:event_tbxNameKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnLogIn1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogIn1MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogIn1MouseReleased

    private void btnLogIn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogIn1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnLogIn1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserSignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogIn1;
    private javax.swing.JComboBox<String> cboxType;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JPasswordField passbox;
    private javax.swing.JTextField tbxAddress;
    private javax.swing.JTextField tbxMob;
    private javax.swing.JTextField tbxName;
    private javax.swing.JTextField tbxProductKey;
    // End of variables declaration//GEN-END:variables
}
