/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PrintAndDesign;

import DBmanage.DBconnProduct;
import DBmanage.DBconnVoucherDetails;
import MainPackeg.ProductInfo;
import MainPackeg.VoucherDetails;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
//import com.sun.xml.internal.ws.api.streaming.XMLStreamReaderFactory;
import java.io.FileOutputStream;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author romio-pc
 */
public class itextpdfmaker extends javax.swing.JFrame {
    //DefaultTableModel t1;
    DBconnProduct pro=new DBconnProduct();
    DBconnVoucherDetails vd=new DBconnVoucherDetails();
    /**
     * Creates new form itextpdfmaker
     */
    public itextpdfmaker() {
        initComponents();
       // t1 = (DefaultTableModel) tblvd.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblvd = new javax.swing.JTable();
        tbxvn = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Tap it");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblvd.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        tblvd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product  ID", "Product Name", "Quantity", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblvd);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(tbxvn, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(tbxvn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //t1 = (DefaultTableModel) tblvd.getModel();
        
        //t1.setRowCount(0);
        
        
        //Object[] row={id,nam,q,tprice};
        //t1.addRow(row);
        
        
        try{
        Document doc=new Document();
        PdfWriter.getInstance(doc, new FileOutputStream("printpdf.pdf"));
        PdfPTable table=new PdfPTable(4);
        doc.open();
        Paragraph header1=new Paragraph("This is the Header",FontFactory.getFont(FontFactory.HELVETICA_BOLD,18,Font.BOLD,BaseColor.MAGENTA));
        header1.setAlignment(Element.ALIGN_CENTER);
        doc.add(header1);        
        Paragraph dotedline = new Paragraph("--------------------------------------------------------");
        dotedline.setAlignment(Element.ALIGN_CENTER);
        doc.add(dotedline);
        doc.add(new Paragraph(".      "));
        table.addCell("Product Id");
        table.addCell("Product Name");
        table.addCell("Quantity");
        table.addCell("Price");
        
        ArrayList<VoucherDetails> list =new ArrayList();       
        list= vd.fullVoucherDetails(tbxvn.getText());
        for(int i=0;i<list.size();i++){
        String id=String.valueOf(list.get(i).getPid());
        int q=list.get(i).getQuant(); 
        ArrayList<ProductInfo> list2 =new ArrayList();
        list2=pro.searchProductForSale(id);
        String nam=list2.get(0).getPname();
        String cst=list2.get(0).getCost();
        double cost=Double.parseDouble(cst);
        String prof=list2.get(0).getProfit();
        double profit=Double.parseDouble(prof);
        double price=(cost+(cost*(profit/100)));
        double tprice=(q*price);
        
        table.addCell(id);
        table.addCell(nam);
        table.addCell(q+"");
        table.addCell(tprice+"");
        }
        
        
        doc.add(table);
        doc.close();
        }
        catch(Exception e){
        }
        
        try {
            Runtime.getRuntime().exec("rundll32 url.dll, FileProtocolHandler printpdf.pdf");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(itextpdfmaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(itextpdfmaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(itextpdfmaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(itextpdfmaker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new itextpdfmaker().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblvd;
    private javax.swing.JTextField tbxvn;
    // End of variables declaration//GEN-END:variables
}
